ClothesPlay/ClothesPlay/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clothes.urls',namespace='clothes')),
]

ClothesPlay/clothes/urls.py
from django.conf.urls import url

from clothes import views

urlpatterns =[
    url(r'^$',views.index,name='index'),
    # 登录
    url(r'^land/$',views.land,name='land'),
    # 注册
    url(r'^register/$',views.register,name='register'),
    # 验证用户名是否存在
    url(r'^checkname/$',views.checkname,name='checkname'),
    # 退出
    url(r'^logout/$',views.logout,name='logout'),
    # 商品详情
    url(r'^gooddetail/(\d+)/$',views.gooddetail,name='gooddetail'),
    # 验证用户是否登录
    url(r'^yangzheng/$', views.yangzheng, name='yangzheng'),
    # 添加商品到购物车
    url(r'^addgoodcard/$',views.addgoodcard,name='addgoodcard'),
    # 购物车页面
    url(r'^cart/$',views.cart,name='cart'),
    #　当购物车里的商品里的数量发生改变
    url(r'^cartsave/$',views.cartsave,name='cartsave'),
    # 购物车里，删除单个
    url(r'^cartdelsave/$',views.cartdelsave,name='cartdelsave'),
    # 购物车里，删除全部
    url(r'^cartdelall/$',views.cartdelall,name='cartdelall'),
    # 购物车里的商品，状态发生改变
    url(r'^cartchangestatus/$',views.cartchangestatus,name='cartchangestatus'),

    url(r'^ming/$',views.ming,name='ming'),

    url(r'^saveimg/$',views.saveimg,name='saveimg'),
    # 生成订单
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    # 订单详情
    url(r'^order/(.+)/$',views.order,name='order'),
    # 服务器接收到支付宝发来的信号，即支付成功
    url(r'^appnotify/$', views.appnotify, name='appnotify'),
    # 生成支付宝付款链接
    url(r'^pay/$', views.pay, name='pay'),  # 支付
    # 支付成功后客户端跳转的页面
    url(r'^returnview/$', views.returnview, name='returnview'),




]

ClothesPlay/clothes/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username =models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    token = models.CharField(max_length=255)
    headimg = models.CharField(max_length=100,default='img/imgs/desk.jpg')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'

class Brand(models.Model):
    img = models.CharField(max_length=200)

    class Meta:
        db_table = 'brand'

class Big(models.Model):
    img = models.CharField(max_length=200)
    class Meta:
        db_table = 'big'

class Good(models.Model):
    # 商品
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    old_price = models.DecimalField(max_digits=10,decimal_places=2,null=True)
    discount = models.FloatField(null=True)
    imgdir = models.CharField(max_length=200)
    # 品牌
    brand_id = models.ForeignKey(Brand,null=True)
    # 大图
    big_id = models.ForeignKey(Big,null=True)
    # 类别
    category_id = models.IntegerField(null=True)

    class Meta:
        db_table = 'good'

# class Base(models.Model):
#     name = models.CharField(max_length=100)
#     price = models.DecimalField(max_digits=10,decimal_places=2)
#     old_price = models.DecimalField(max_digits=10,decimal_places=2)
#     discount = models.FloatField()
#     imgdir = models.CharField(max_length=200)
#
#     class Meta():
#         abstract=True
#
# class Good(Base):
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         db_table = 'good'
#
#
# class Wheel1(Base):
#     class Meta:
#         db_table = 'wheel1'
#
# class Wheel2(Base):
#     class Meta:
#         db_table = 'wheel2'
# class Wheel3(Base):
#     class Meta:
#         db_table = 'wheel3'
#
class Cart(models.Model):
    user = models.ForeignKey(User)
    goodnum = models.IntegerField()
    goodcolor = models.CharField(max_length=20)
    goodsize = models.CharField(max_length=20)
    good = models.ForeignKey(Good)
    isselect = models.BooleanField(default=True)
    class Meta:
        db_table = 'cart'

class Base(models.Model):
    name = models.CharField(max_length=200)
    img = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    class Meta:
        abstract=True


class Woman(Base):
    class Meta:
        db_table = 'woman'

class Man(Base):
    class Meta:
        db_table = 'man'

class Child(Base):
    class Meta:
        db_table = 'child'


class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 状态
    # 0 未付款
    # 1 已付款
    status = models.IntegerField(default=0)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 订单号
    identifier = models.CharField(max_length=256)

    class Meta:
        db_table = 'order'



# 订单商品 模型类
# 一个订单 对应 多个商品
class OrderGood(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    good = models.ForeignKey(Good)
    # 商品规格
    number = models.IntegerField()

    size = models.CharField(max_length=20)

    color = models.CharField(max_length=20)

    class Meta:
        db_table = 'ordergood'

ClothesPlay/templates/SHOP_Cart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link href="{% static 'css/shoppingCart.css' %}" type="text/css" rel="stylesheet" />
		<style>
			@font-face {
			  font-family: 'iconfont';
			  src: url('{% static 'font/iconfont.eot' %}'); /* IE9*/
			  src: url('{% static 'font/iconfont.eot?#iefix' %}') format('embedded-opentype'), /* IE6-IE8 */
			  url('{% static 'font/iconfont.woff' %}') format('woff'), /* chrome、firefox */
			  url('{% static 'font/iconfont.ttf' %}') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
			  url('{% static 'font/iconfont.svg#iconfont' %}') format('svg'); /* iOS 4.1- */
			}
			.I-ico{
			    font-family:"iconfont" !important;
			    font-size:16px;font-style:normal;
			    -webkit-font-smoothing: antialiased;
			    -webkit-text-stroke-width: 0.2px;
			    -moz-osx-font-smoothing: grayscale;		    
			 }
			*{margin: 0px; padding: 0px;}
			body,html{font-size: 12px; margin: 0 auto;}
			body{width: 1263px; height:auto;}
			a{text-decoration: none;}
			li{list-style-type: none;}
			/*头部（g-hd）部分*/
			#j_topbar{width: 1263px; height:30px;background: #F9F9F9;}
			#j_topbar .g-top{width: 1190px; line-height: 30px; margin: 0px 36.5px;}
			.g-topL{width: 260px; height: 30px; float: left;}
			.indexs,.land,.register{color: #666}
			.g-topR{width: 404px; height: 30px; float: right;}
			.g-topR a{ color: #666;}
			.g-topR i{font-style: normal; color: #ddd;}
			.hd{width: 1263px; height: 138px; background: #fff;}
			.top{width: 1190px; height: 60px; margin: 0px 36.5px; padding:20px 0px ;}
			.top .logo{float: left;}
			.top .top-sch{width: 350px; height: 60px; float: right;}
			.top .top-sch .form-box{border: 2px solid #f10582;}
			.top .top-sch .form-box .u-sch-text{width: 246px; height: 24px; padding: 5px 0px; margin-left: 20px; border: 0px;outline:none}
			.top .top-sch .form-box .u-sch-btn{width: 74px;height: 34px; background:#f10582 ; color: white; border:0px ; float: right;}
			.top .top-sch .sch-keywords{margin-top: 10px; width: 350px; height: 18px;}
			.top .top-sch .sch-keywords span,a {color: #999;}
			.hd .shop_m-nav{width: 1263px; height: 36px; background: #EB2323;}
			.hd .shop_m-nav .top_nav{width: 1190px; height: 36px; display: block; margin: 0 auto;}
			.hd .shop_m-nav .top_nav li a{color: white; font-size:14px; font-weight:500;float: left; display: inline-block; width: 99px;line-height: 36px; text-align: center;}
			.hd .shop_m-nav .top_nav li a:hover{background: #db0a76;}
            .butt{
               display: inline-block;height: 26px; width: 26px; border:1px solid #c7c7c7;text-align: center; line-height: 26px;
            }
            #num{
                width: 30px; height: 22px; padding: 2px 5px; border: 1px solid #c7c7c7;outline:none;text-align: center;
            }
		</style>
		<script src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script src="{% static 'js/jquery.cookie.js' %}"></script>
		<script src="{% static 'js/shops_cart.js' %}"></script>
		<script src="{% static 'js/cart.js' %}"></script>
	</head>
	<body>
		<div class="g-hd">
			<!--头部公共部分-->
            <div id="j_topbar" class="m-topbar f-cb">
            	<div class="g-top">
            		<div class="g-topL">
	            		<a href="{% url 'clothes:index' %}" class="indexs">
	            			<span class="I-ico" style="color: #f10582;">&#xe73d;</span> 衣扮网首页	
	            		</a>
	            		{% if username %}
                            <a href="#">{{ username }}</a>
                            <a href="{% url 'clothes:logout' %}" class="logout">
	            			[退出]
	            		    </a>
                        {% else %}
                            <a href="{% url 'clothes:land' %}" class="land">
	            			[登录]
	            		    </a>
	            		    <a href="{% url 'clothes:register' %}" class="register">
	            			[免费注册]
	            		    </a>
                        {% endif %}
            		</div>          	            		
            		<div class="g-topR">
            			<a href="#" target="_blank" style="color: #f10582;">下载app&nbsp;</a>
            			<a href="#" target="_blank">我的订单</a> <i>|</i>
            			<a href="{% url 'clothes:cart' %}" target="_blank">
            				<span class="I-ico" style="color: #f10582;">&#xe95f;</span>购物车
                            {% if goodsnum.goodnum__sum %}
                                {{ goodsnum.goodnum__sum }}
                            {% else %}
                                0
                            {% endif %}
                            件
            			</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico"style="color: gold;">&#xeaaa;</span>收藏夹
            			</a> <i>|</i>
            			<a href="#" target="_blank">互联支付</a> <i>|</i>
            			<a href="#" target="_blank">帮助中心</a>
            		</div>
            	</div>
            </div>           
            <div class="hd">
            	<!--搜索栏-->
            	<div class="top">
            		<div class="logo"><a href="{% url 'clothes:index' %}" target="_blank"><img src="{% static 'img/imgs/logo.png' %}"/></a></div>
            		<div class="top-sch">
            			<div class="form-box">
            				<form style="position: relative;">
            					<span class="I-ico" style="position: absolute; top: 10px; left: 5px;">&#xe679;</span>
            					<input type="text" class="u-sch-text" placeholder="请输入您要搜的商品关键字！"/>
            					<input type="submit" class="u-sch-btn" value="搜 索" />
            				</form>
            			</div>
            			<div class="sch-keywords">
            				<span >热门搜索：</span>
            				<a href="#">连衣裙&nbsp;</a>
            				<a href="#">T桖&nbsp;</a>
            				<a href="#">POLO衫&nbsp;</a>
            				<a href="#">短裙&nbsp;</a>
            				<a href="#">半短裙&nbsp;</a>
            			</div>
            		</div>
            	</div>
            	<div class="shop_m-nav">
            		<ul class="top_nav">
            			<li><a href="{% url 'clothes:index' %}">首页</a></li>
            			<li><a href="">女装特卖</a></li>
            			<li><a href="">男装特卖</a></li>
            			<li><a href="">童装特卖</a></li>
            			<li><a href="">内衣特卖</a></li>
            			<li><a href=""><span class="I-ico">&#xe6e0;</span> 限时特卖</a></li>
            			<li><a href="">明星穿搭秘籍</a></li>
            			<li><a href="">美衣盒子</a><img style="position: absolute; left: 800px; top: 120px;" src="{% static 'img/imgs/hot.gif' %}"/></li>
            		</ul>           		
            	</div>
            </div>	
        </div>
        <div id="my-shopping-cart">
			<div class="cart-text">
				<h1>我的购物车</h1>
				<p>查看购物车商品清单，增加减少商品数量，并勾选想要的商品进入下一步操作。</p>
			</div>
			<div id="shopCar" class="shoppping-cart-content">
				<table>
					<thead>
						<tr class="shoppping-cart-content-head">
                            <td class="w80">选择</td>
							<td class="w80">序号(商品ID)</td>
							<td class="w560">商品</td>
							<td class="w80">单价(元)</td>
							<td class="w120">数量</td>
							<td class="w80">小计(元)</td>
							<td class="w80">操作</td>
						</tr>
                        {% for good in goods %}
                            <tr class="shoppping-cart-content-head good">
                                <td class="w80"><input type="checkbox" class="good_s" ></td>
{#                                商品id#}
                                <td class="w80">{{ forloop.counter }}</td>
{#                                商品名#}
                                <td class="w560"><a href="{% url 'clothes:gooddetail' good.good.id %}">
                                    <span>{{ good.good.name }}</span>
                                    <span>&nbsp;&nbsp;{{ good.goodcolor }}</span>
                                    <span>&nbsp;&nbsp;{{ good.goodsize }}</span>
                                </a></td>

{#                                商品单价#}
                                <td class="w80">{{ good.good.price }}</td>
                                <td class="w120">
                                    <a href="javaScript:void(0)" class="butt prev" id="">-</a>
{#                                    商品数量#}
                                    <input type="text" class="num" id="num" value="{{ good.goodnum }}">
                                    <a href="javaScript:void(0)" class="butt add" id="">+</a>
                                </td>
                                {#商品数量#}
                                <td class="w80 goodprice">{% widthratio good.goodnum 1.00 good.good.price %}.00</td>
                                <td class="w80"><input type="button" class="del" value="删除" ></td>
						    </tr>
                        {% endfor %}

					</thead>
					<tbody>
						<th class="shoppping-cart-content-title" colspan="6">
							<div class="store-title">序号:</div>
							<div class="store-activity"><a href="">店铺活动，满29免运费</a></div>
						</th>
	
					</tbody>
					<tfoot>
						<th class="tstore-totle-money" colspan="6">
							<div class="TTM-text">商品合计:</div>
							<div class="TTM-all-money"><span></span>元</div>
						</th>
					</tfoot> 
	
				</table>
					
				<div class="totle-money-text">商品总价(不含运费) <span id="totalPrice"></span>元</div>
				<div class="next-step">
					<div class="next-step-tetx">
						<a href="{% static 'orderPage/orderPage.html' %}">
							<div class="NST-bg"><img src="{% static 'img/imgs/next.jpg' %}"/></div>
							<span>下一步，填写核对购物信息</span>
						</a>
					</div>
	
				</div>
				<div class="gest-you-like">猜您喜欢的宝贝</div>
				<div class="show-you"></div>								
			</div>
	</div>

	</body>
</html>

ClothesPlay/templates/ming.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
{#    <link rel="stylesheet" href="https://3.swiper.com.cn/dist/css/swiper.min.css">#}

    <style>
        .name{font-size: 30px;}
        img{width: 300px;height: 300px;border-radius: 50%;}
        
    
    </style>
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
{#    <script>#}
{#        $(function () {#}
{#            $('.but').click(function () {#}
{#                imgobj = document.getElementsByClassName('img');#}
{#                var form = new FormData();#}
{#                form.append('img',imgobj);#}
{##}
{#                $.ajax({#}
{#                    'url':'{% url 'clothes:saveimg' %}',#}
{#                    'type':'get',#}
{#                    'data':form,#}
{#                    'processData':false,#}
{#                    'contentType':false,#}
{#                    success:function (data) {#}
{#                        alert('ok')#}
{#                    }#}
{#                })#}
{#            })#}
{#        })#}
{#    </script>#}
</head>
<body>
    <div class="startimg">
        <div class="name">用户名：{{ user.username }}</div>
        <div><h2> 头像：</h2></div>
       <img src="{% static user.headimg %}" alt="">
        <br>
        <form action="{% url 'clothes:saveimg' %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <input type="file" name="img" value="上传图片">
        <input type="submit" class="but" value="提交">
        </form>
    </div>
</body>
</html>

ClothesPlay/templates/order.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>我的订单</title>
		<link href="{% static 'css/shoppingCart.css' %}" type="text/css" rel="stylesheet" />
		<style>
			@font-face {
			  font-family: 'iconfont';
			  src: url('{% static 'font/iconfont.eot' %}'); /* IE9*/
			  src: url('{% static 'font/iconfont.eot?#iefix' %}') format('embedded-opentype'), /* IE6-IE8 */
			  url('{% static 'font/iconfont.woff' %}') format('woff'), /* chrome、firefox */
			  url('{% static 'font/iconfont.ttf' %}') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
			  url('{% static 'font/iconfont.svg#iconfont' %}') format('svg'); /* iOS 4.1- */
			}
			.I-ico{
			    font-family:"iconfont" !important;
			    font-size:16px;font-style:normal;
			    -webkit-font-smoothing: antialiased;
			    -webkit-text-stroke-width: 0.2px;
			    -moz-osx-font-smoothing: grayscale;
			 }
			*{margin: 0px; padding: 0px;}
			body,html{font-size: 12px; margin: 0 auto;}
			body{width: 1263px; height:auto;}
			a{text-decoration: none;}
			li{list-style-type: none;}
			/*头部（g-hd）部分*/
			#j_topbar{width: 1263px; height:30px;background: #F9F9F9;}
			#j_topbar .g-top{width: 1190px; line-height: 30px; margin: 0px 36.5px;}
			.g-topL{width: 260px; height: 30px; float: left;}
			.indexs,.land,.register{color: #666}
			.g-topR{width: 404px; height: 30px; float: right;}
			.g-topR a{ color: #666;}
			.g-topR i{font-style: normal; color: #ddd;}
			.hd{width: 1263px; height: 138px; background: #fff;}
			.top{width: 1190px; height: 60px; margin: 0px 36.5px; padding:20px 0px ;}
			.top .logo{float: left;}
			.top .top-sch{width: 350px; height: 60px; float: right;}
			.top .top-sch .form-box{border: 2px solid #f10582;}
			.top .top-sch .form-box .u-sch-text{width: 246px; height: 24px; padding: 5px 0px; margin-left: 20px; border: 0px;outline:none}
			.top .top-sch .form-box .u-sch-btn{width: 74px;height: 34px; background:#f10582 ; color: white; border:0px ; float: right;}
			.top .top-sch .sch-keywords{margin-top: 10px; width: 350px; height: 18px;}
			.top .top-sch .sch-keywords span,a {color: #999;}
			.hd .shop_m-nav{width: 1263px; height: 36px; background: #EB2323;}
			.hd .shop_m-nav .top_nav{width: 1190px; height: 36px; display: block; margin: 0 auto;}
			.hd .shop_m-nav .top_nav li a{color: white; font-size:14px; font-weight:500;float: left; display: inline-block; width: 99px;line-height: 36px; text-align: center;}
			.hd .shop_m-nav .top_nav li a:hover{background: #db0a76;}
		</style>
		<script src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script src="{% static 'js/jquery.cookie.js' %}"></script>
		<script src="{% static 'js/shops_cart.js' %}"></script>
{#		<script src="{% static 'js/cart.js' %}"></script>#}
        <script>
            $(function () {
                var sum = 0;
                $('.oneprice').each(function () {
                    sum1 = $(this).html()
                    sum = sum+parseInt(sum1)
                    console.log(sum)

            })
                $('#totalPrice').html(sum+'.00')

                $('#pay').click(function () {
                    var identifier = $(this).attr('identifier')
                    data = {
                        'identifier':identifier
                    }
                    console.log(identifier)
                    $.get('/pay/', data, function (response) {
                        console.log(response)
                        if (response.status == 1){
                            window.open(response.alipayurl, target='_self')
                    }
        })
    })
})




        </script>
	</head>
	<body>
		<div class="g-hd">
			<!--头部公共部分-->
            <div id="j_topbar" class="m-topbar f-cb">
            	<div class="g-top">
            		<div class="g-topL">
	            		<a href="{% url 'clothes:index' %}" class="indexs">
	            			<span class="I-ico" style="color: #f10582;">&#xe73d;</span> 衣扮网首页
	            		</a>
	            		{% if username %}
                            <a href="#">{{ username }}</a>
                            <a href="{% url 'clothes:logout' %}" class="logout">
	            			[退出]
	            		    </a>
                        {% else %}
                            <a href="{% url 'clothes:land' %}" class="land">
	            			[登录]
	            		    </a>
	            		    <a href="{% url 'clothes:register' %}" class="register">
	            			[免费注册]
	            		    </a>
                        {% endif %}
            		</div>
            		<div class="g-topR">
            			<a href="#" target="_blank" style="color: #f10582;">下载app&nbsp;</a>
            			<a href="#" target="_blank">我的订单</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico" style="color: #f10582;">&#xe95f;</span>购物车0件
            			</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico"style="color: gold;">&#xeaaa;</span>收藏夹
            			</a> <i>|</i>
            			<a href="#" target="_blank">互联支付</a> <i>|</i>
            			<a href="#" target="_blank">帮助中心</a>
            		</div>
            	</div>
            </div>
            <div class="hd">
            	<!--搜索栏-->
            	<div class="top">
            		<div class="logo"><a href="{% url 'clothes:index' %}" target="_blank"><img src="{% static 'img/imgs/logo.png' %}"/></a></div>
            		<div class="top-sch">
            			<div class="form-box">
            				<form style="position: relative;">
            					<span class="I-ico" style="position: absolute; top: 10px; left: 5px;">&#xe679;</span>
            					<input type="text" class="u-sch-text" placeholder="请输入您要搜的商品关键字！"/>
            					<input type="submit" class="u-sch-btn" value="搜 索" />
            				</form>
            			</div>
            			<div class="sch-keywords">
            				<span >热门搜索：</span>
            				<a href="#">连衣裙&nbsp;</a>
            				<a href="#">T桖&nbsp;</a>
            				<a href="#">POLO衫&nbsp;</a>
            				<a href="#">短裙&nbsp;</a>
            				<a href="#">半短裙&nbsp;</a>
            			</div>
            		</div>
            	</div>
            	<div class="shop_m-nav">
            		<ul class="top_nav">
            			<li><a href="index.html">首页</a></li>
            			<li><a href="">女装特卖</a></li>
            			<li><a href="">男装特卖</a></li>
            			<li><a href="">童装特卖</a></li>
            			<li><a href="">内衣特卖</a></li>
            			<li><a href=""><span class="I-ico">&#xe6e0;</span> 限时特卖</a></li>
            			<li><a href="">明星穿搭秘籍</a></li>
            			<li><a href="">美衣盒子</a><img style="position: absolute; left: 800px; top: 120px;" src="{% static 'img/imgs/hot.gif' %}"/></li>
            		</ul>
            	</div>
            </div>
        </div>
        <div id="my-shopping-cart">
			<div class="cart-text">
				<h1>我的订单   编号:  {{ order.identifier }}</h1>
				<p>查看订单，并进入下一步操作。
                状态:
            <span style="background: red; color: white;font-size: 15px">
                {% if order.status == 0 %}
                    未付款
                {% elif order.status == 1 %}
                    已付款
                {% endif %}
            </span>
                </p>

			</div>
			<div id="shopCar" class="shoppping-cart-content">
				<table>
					<thead>
						<tr class="shoppping-cart-content-head">
							<td class="w80">序号(商品ID)</td>
							<td class="w560">商品</td>
							<td class="w80">单价(元)</td>
							<td class="w120">数量</td>
							<td class="w80">小计(元)</td>
						</tr>
                        {% for ordergood in order.ordergood_set.all %}
                            <tr class="shoppping-cart-content-head">
                                <td class="w80">{{ forloop.counter }}</td>
                                <td class="w560">{{ ordergood.good.name }}
                                    &nbsp;<span>{{ ordergood.color }}</span>
                                    &nbsp;<span>{{ ordergood.size }}</span>
                                </td>
                                <td class="w80">{{ ordergood.good.price }}(元)</td>
                                <td class="w120">{{ ordergood.number }}</td>
                                <td class="w80 oneprice">{% widthratio ordergood.number 1.00 ordergood.good.price %}.00</td>
						    </tr>
                        {% endfor %}

					</thead>
					<tbody>
					</tbody>
					<tfoot>
						<th class="tstore-totle-money" colspan="6">
						</th>
					</tfoot>

				</table>

				<div class="totle-money-text">商品总价(不含运费) <span id="totalPrice"></span>元</div>
				<div class="next-step">
					<div class="next-step-tetx">
						<div id="pay" identifier="{{ order.identifier }}">
							<div class="NST-bg"><img src="{% static 'img/imgs/next.jpg' %}"/></div>
							<span style="margin-left: 60px">付款</span>
						</a>
					</div>
	
				</div>
				<div class="gest-you-like">猜您喜欢的宝贝</div>
				<div class="show-you"></div>								
			</div>
	</div>

	</body>
</html>